name: Build and Deploy to Render

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: idris257/blog_api:latest
      RENDER_SERVICE_ID: srv-d3rsdfc9c44c73avlgj0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: idris257
          password: Idris@25762


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Trigger Render deployment
        run: |
          echo "🚀 Triggering Render deployment..."
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "accept: application/json" \
            -H "authorization: Bearer rnd_qXEEHdMmlqjEHUM6PhFhtfOreYLK"


