name: Django Seed

on:
  workflow_run:
    workflows: ["Django Migrate"]
    types:
      - completed

jobs:
  seed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Seed database
        run: python manage.py seed_data
