name: Django Migrate

on:
  workflow_run:
    workflows: ["Django Test"]
    types:
      - completed

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Apply migrations
        run: python manage.py migrate --noinput
